name: ExoticGarden
version: 1.6.3
authors: [mrCookieSlime, Goldentoenail, Joapple]
description: A Slimefun Addon that adds new Plants and dishes to the game
website: http://TheBusyBiscuit.github.io/

main: me.mrCookieSlime.ExoticGarden.ExoticGarden

depend: [Slimefun]
softdepend: [CS-CoreLib, Sanity, Residence]
commands:
  exotic:
    description: ExoticGarden's command
    aliases: [exo]